version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y rsync
      - run: ./mkdist
      - run: npx --package=@percy/agent percy snapshot dist/ --ignore-files '**/bg/**/*'
